// src/components/forms/LoginForm/index.tsx
import React from 'react';
import { Formik } from 'formik';
import { Link } from '@reach/router';
import { Input, Button, Typography } from 'antd';
import { UserDTO } from 'services/models';
import FormErrors from 'components/forms/FormErrors';
import { useDispatch } from 'store';
import { login } from 'store/modules/user/actions';
import LoginSchema from './schema';
import styles from './LoginForm.module.sass';

const { Text } = Typography;

const LoginForm: React.FC = () => {
  const dispatch = useDispatch();

  const initialValues = {
    email: '',
    password: '',
  };

  const onSubmit = (data: UserDTO) => dispatch(login(data));

  return (
    <Formik {...{ initialValues, onSubmit, validationSchema: LoginSchema }}>
      {({ handleSubmit, getFieldProps, errors }) => (
        <form action="" onSubmit={handleSubmit}>
          <FormErrors errors={errors} />
          <Input
            className={styles.input}
            type="email"
            placeholder="Email..."
            {...getFieldProps('email')}
          />
          <Input
            className={styles.input}
            type="password"
            placeholder="Пароль..."
            {...getFieldProps('password')}
          />
          <Button className={styles.button} type="primary" htmlType="submit">
            Войти
          </Button>
          <div className={styles.signup}>
            <Text>Или</Text>
            <Link to="/signup"> зарегистрироваться</Link>
          </div>
        </form>
      )}
    </Formik>
  );
};

export default LoginForm;

// app/src/components/loginForm/LoginForm.vue
<template>
  <b-form class="login-form">
    <b-form-group id="group-name" label="Ваше имя:" label-for="name">
      <b-form-input
        id="name"
        required
        placeholder="Ваше имя"
      ></b-form-input>
    </b-form-group>

    <b-form-group id="group-password" label="Пароль:" label-for="password">
      <b-form-input
        id="password"
        type="password"
        required
        placeholder="Пароль"
      ></b-form-input>
    </b-form-group>

    <b-button class="col-12" type="submit" variant="primary">Войти</b-button>

    <p class="text-center mt-2">или <b-link to="/signup">Зарегистрироваться</b-link></p>
  </b-form>
</template>

<script>

export default {
  name: 'LoginForm',
}
</script>


<style scoped lang="scss">
.login-form {
  width: 500px;
  margin: 0 auto;
}
</style>
