// app/src/components/signupForm/SignUpForm.vue
<template>
  <b-form class="signup-form">
    <b-form-group
      id="group-email"
      label="Email:"
      label-for="email"
    >
      <b-form-input
        id="email"
        type="email"
        required
        placeholder="Введите Email"
      ></b-form-input>
    </b-form-group>

    <b-form-group id="group-name" label="Ваше имя:" label-for="name">
      <b-form-input
        id="name"
        required
        placeholder="Ваше имя"
      ></b-form-input>
    </b-form-group>

    <b-form-group id="group-password" label="Пароль:" label-for="password">
      <b-form-input
        id="password"
        type="password"
        required
        placeholder="Пароль"
      ></b-form-input>
    </b-form-group>

    <b-button class="col-12" type="submit" variant="primary">Зарегистрироваться</b-button>

    <p class="text-center mt-2">или <b-link to="/login">Войти</b-link></p>
  </b-form>
</template>

<script>

export default {
  name: 'SignUpForm'
}
</script>

<style scoped lang="scss">
  .signup-form {
    width: 500px;
    margin: 0 auto;
  }
</style>

// src/components/forms/SignupForm/index.tsx
import React from 'react';
import { useFormik } from 'formik';
import { Link as RouterLink } from '@reach/router';
import { Input, Alert, Button, Typography } from 'antd';
import SignupSchema from './schema';
import styles from './SignupForm.module.sass';

const { Text } = Typography;

interface ISignupFormValues {
  email: string;
  name: string;
  password: string;
}

const SignupForm: React.FC = () => {
  const { getFieldProps, handleSubmit, errors, touched } = useFormik<ISignupFormValues>({
    initialValues: {
      email: '',
      name: '',
      password: '',
    },
    validationSchema: SignupSchema,
    onSubmit(data) {
      console.log(data);
    },
  });

  return (
    <form action="" onSubmit={handleSubmit}>
      {errors.email && touched.email && (
        <Alert className={styles.error} type="error" message={errors.email} />
      )}
      {errors.name && touched.name && (
        <Alert className={styles.error} type="error" message={errors.name} />
      )}
      {errors.password && touched.password && (
        <Alert className={styles.error} type="error" message={errors.password} />
      )}
      <Input
        className={styles.input}
        type="email"
        placeholder="Email..."
        {...getFieldProps('email')}
      />
      <Input className={styles.input} type="name" placeholder="Имя..." {...getFieldProps('name')} />
      <Input
        className={styles.input}
        type="password"
        placeholder="Пароль..."
        {...getFieldProps('password')}
      />
      <Button className={styles.button} type="primary">
        Зарегистрироваться
      </Button>
      <div className={styles.login}>
        <Text>Или</Text>
        <RouterLink to="/login"> войти</RouterLink>
      </div>
    </form>
  );
};

export default SignupForm;
